// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Board = require("./Board.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Button = require("./Button.js");
var Js_math = require("bs-platform/lib/js/js_math.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var initialState = /* record */[
  /* score */0,
  /* status : Stopped */1,
  /* activeMole : Inactive */0
];

var component = ReasonReact.reducerComponent("App");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1][/* status */1];
              return React.createElement("div", {
                          className: "app"
                        }, React.createElement("div", {
                              className: "game"
                            }, "hello reason"), match ? ReasonReact.element(undefined, undefined, Button.make("Start game !", (function (_click) {
                                      return Curry._1(self[/* send */3], /* Start */0);
                                    }), /* array */[])) : ReasonReact.element(undefined, undefined, Board.make(self[/* state */1][/* activeMole */2], /* array */[])));
            }),
          /* initialState */(function (param) {
              return initialState;
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (typeof action === "number") {
                switch (action) {
                  case 0 : 
                      return /* UpdateWithSideEffects */Block.__(2, [
                                /* record */[
                                  /* score */state[/* score */0],
                                  /* status : Started */0,
                                  /* activeMole */state[/* activeMole */2]
                                ],
                                (function (self) {
                                    setInterval((function (param) {
                                            var randomInt = Js_math.random_int(0, 9);
                                            return Curry._1(self[/* send */3], /* ChangeActiveMole */[randomInt]);
                                          }), 1000);
                                    return /* () */0;
                                  })
                              ]);
                  case 1 : 
                      return /* Update */Block.__(0, [/* record */[
                                  /* score */state[/* score */0],
                                  /* status : Stopped */1,
                                  /* activeMole : Inactive */0
                                ]]);
                  case 2 : 
                      return /* Update */Block.__(0, [/* record */[
                                  /* score */state[/* score */0],
                                  /* status */state[/* status */1],
                                  /* activeMole : Inactive */0
                                ]]);
                  
                }
              } else {
                return /* Update */Block.__(0, [/* record */[
                            /* score */state[/* score */0],
                            /* status */state[/* status */1],
                            /* activeMole : Active */[action[0]]
                          ]]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.initialState = initialState;
exports.component = component;
exports.make = make;
/* component Not a pure module */
