// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Board");

var items = Belt_Array.range(0, 9);

function make(activeMole, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", {
                          className: "board"
                        }, Belt_Array.map(items, (function (item) {
                                var tmp;
                                var exit = 0;
                                if (activeMole && activeMole[0] === item) {
                                  tmp = React.createElement("div", {
                                        className: "mole visible"
                                      });
                                } else {
                                  exit = 1;
                                }
                                if (exit === 1) {
                                  tmp = React.createElement("div", {
                                        className: "mole"
                                      });
                                }
                                return React.createElement("div", {
                                            key: String(item),
                                            className: "board-item"
                                          }, tmp, React.createElement("div", {
                                                className: "ground"
                                              }));
                              })));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.items = items;
exports.make = make;
/* component Not a pure module */
